### ISSUE TITLE
SSH key

### ISSUE THREAD

**Issue by sarroyo551** [learn-co-curriculum/phase-0-macos-env-git-github#6]
It was unclear which part to copy and paste to make an SSH key since when the instructor did it it was blurred out.

**Comment by lizbur10** [comment]
Hi @sarroyo551 ! We are not able to show the actual key in the video because it is secure information, but you should be able to complete the steps without seeing the key itself. 

When you enter the command `cat ~/.ssh/id_rsa.pub ` in the terminal (step 8 in the written instructions), that copies the key to the clipboard. Then you go to the GitHub New SSH Key Form, click in the "Key" input field, and type cmd-V (for Mac) or ctrl-V (for Windows) to paste it in.

If you are having difficulties getting it configured, you can use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team

Thanks for contributing to the Flatiron School curriculum 💙
